# Homework 1 - Part 1

In [1]:
# Used libraries
import numpy as np
import math
import os
import random
import re
import sys

## Introduction

#### Say 'Hello world' with Python

In [2]:
if __name__ == '__main__':
    my_string = "Hello, World!"
    print(my_string)

Hello, World!


#### Python if-else

In [4]:
# Python if-else
if __name__ == '__main__':
    n = int(input().strip())
    
    # if n is odd or n is in the range of 6 to 20, print Weird
    # else print not weird
    if ((n%2)!= 0) or ((n>=6) and (n<=20)):
        print('Weird')
    else:
        print('Not Weird')

2
Not Weird


#### Arithmetic operators

In [5]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    # execute the three operators (sum, difference, and product)
    sumOperator = a + b
    difference = a - b
    product = a*b
    
    # print the three operators
    print(sumOperator)
    print(difference)
    print(product)

2
3
5
-1
6


#### Python: division

In [ ]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    
    # determine the interger division and float division
    integerDiv = a//b
    floatDiv = a/b
    
    # print both values
    print(integerDiv)
    print(floatDiv)

#### Loops

In [ ]:
if __name__ == '__main__':
    n = int(input())
    
    # loop over the numbers up till n.
    # print the square of n
    for i in range(n):
        print(i**2)

#### Write a function

In [1]:
def is_leap(year):
    leap = False
    
    # the year can be evenly divided by zero
    if (year % 4) == 0:
        leap = True
    
    # if the year is divided by 100 and not 400, turn back to false
    if (year % 100) == 0:
        if not (year % 400) == 0:
            leap = False
        
    
    return leap

# test a year and see if it is a leapyear
year = int(input())
print(is_leap(year))

2
False


#### Print function

In [ ]:
if __name__ == '__main__':
    n = int(input())
    
    # print the consecutive numbers on one line
    for i in range(n): 
        print((i + 1),end="") 

## Basic data types

#### List comprehensions

In [2]:
if __name__ == '__main__':
    # The given input variables
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
        
    List = []
    
    # loop over all possible options for the coordinates.
    for i in range(x+1):
        for j in range(y+1):
            for l in range(z+1):
                # check if the sum is not equal to l
                if (i+j+l) != n:
                    List.append([i,j,l])

    print(List)
    

2
2
2
2
[0, 1, 2, 4, 5, 6, 7, 8, 9]
[[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 2], [0, 2, 1], [0, 2, 2], [1, 0, 0], [1, 0, 2], [1, 1, 1], [1, 1, 2], [1, 2, 0], [1, 2, 1], [1, 2, 2], [2, 0, 1], [2, 0, 2], [2, 1, 0], [2, 1, 1], [2, 1, 2], [2, 2, 0], [2, 2, 1], [2, 2, 2]]


#### Find the runner-up score!

In [15]:
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    
    List = list(arr)
    
    #print second highest value
    secValue = max(i for i in List if (i != max(List)))
    print(secValue)

4
5


ValueError: max() arg is an empty sequence

#### Nested lists

In [58]:
from operator import itemgetter

if __name__ == '__main__':
    records = []
    for _ in range(int(input())):
        name = input()
        score = float(input())
        
        # save the name and score in a list
        records.append([name, score])

    # sort the list alphabetically and numerically
    newRecords = sorted(records, key=itemgetter(0))
    newRecords = sorted(newRecords, key=itemgetter(1))

    for i in range(1,len(newRecords),1):
    # find the second biggest nr
    # if found, save the value and break out of loop
        if newRecords[i][1] > newRecords[i-1][1]:
            Value = newRecords[i][1]
            break

    for i in range(len(newRecords)):
        # if the value is equal, print name of student
        if newRecords[i][1] == Value:
            print(newRecords[i][0])


5
Harry
37.21
Berry
37.21
Tina
37.2
Akriti
41
Harsh
39
Harsh


#### Finding the percentage

In [ ]:
if __name__ == '__main__':
    # Function to determine average of a list
    def AVG(List):
        return sum(List) / len(List)
    
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()
    
        
    avgStudent = AVG(student_marks[query_name])
    
    #print average with two decimals
    print("%.2f" % float(avgStudent))



#### Lists

In [4]:
if __name__ == '__main__':
    N = int(input())
    # make an empty list
    lst = []
    # Loop over the N to define the action
    for i in range(N):
        n = input().split()
        action = n[0]
        if action == 'insert':
            lst.insert(int(n[1]),int(n[2]))
        if action == 'print':
            print(lst)
        if action == 'remove':
            lst.remove(int(n[1]))
        if action == 'append':
            lst.append(int(n[1]))
        if action == 'sort':
            lst.sort()
        if action == 'pop':
            lst.pop()
        if action == 'reverse':
            lst.reverse()

4
4
4
4
4


#### Tuples

In [ ]:
if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())
    crTuple = tuple(integer_list)
    print(hash(crTuple))

## Strings

#### sWAP cASE

In [5]:
def swap_case(s):
    # swap lower to upper case and vice versa
    return s.swapcase()

if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

hoI
HOi


#### String split and join

In [ ]:
def split_and_join(line):
    # split the line
    splitLine = line.split(" ")
    # join the line
    joinLine = "-".join(splitLine)
    return joinLine 

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

#### What's your name?

In [ ]:
def print_full_name(first, last):
    return print("Hello " + first + " " + last + "! You just delved into python.")

if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

#### Mutations

In [ ]:
def mutate_string(string, position, character):
    # change the string
    newString = string[:position] + character + string[(position+1):]
    return newString

if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

#### Find a string

In [ ]:
def count_substring(string, sub_string):
        counter = 0 # initialize counter
        subLen = len(sub_string) # determine length of sub string
        for i in range(len(string)):
            if string[i:i+subLen] == sub_string:
                counter += 1
        return counter

        
if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)

#### String validators

In [ ]:
if __name__ == '__main__':
    s = input()
    lst = list(s) # make a list of the input
    # initialize booleans to check if true or not
    alphaNum = False
    alphaBet = False
    digits = False
    lowCase = False
    upCase = False
    
    # check per symbol what it is
    for i in lst:
        if i.isalnum():
            alphaNum = True
        if i.isalpha():
            alphaBet = True
        if i.isdigit():
            digits = True
        if i.islower():
            lowCase = True
        if i.isupper():
            upCase = True
    
    # Print the given statements
    print(alphaNum)
    print(alphaBet)
    print(digits)
    print(lowCase)
    print(upCase)

#### Text alignment

In [25]:
## I used the discussion page of the website, since I did not understand the aim of the assignment.

from math import ceil

T = int(input()) # Thickness
c = 'H'          # Character

#Upper Rectangel
([print (x) for x in [(c*i).rjust(T-1)+c+(c*i).ljust(T-1) for i in range(T)]])

#Upper Stand
([print (x) for x in [((c*T).center(2*T-1)+(" " * (2*T+1))+(c*T).center(2*T-1)) for i in range(T+1)]])

#Bridge
([print (x) for x in [(c*(5*T)).center((6*T)-1) for i in range(int(ceil(T/2)))]])

#Lower Stand
([print (x) for x in [((c*T).center(2*T-1)+(' '  * (2*T+1))+(c*T).center(2*T-1)) for i in range(T+1)]])

#Lower Rectangel
# acually the same as the upper, but with a reversed range(T-1,-1,-1)
([print (x) for x in [(' ' * (4*T))+(c*i).rjust(T-1)+c+(c*i).ljust(T-1) for i in range(T-1,-1,-1)]])

5
    H    
   HHH   
  HHHHH  
 HHHHHHH 
HHHHHHHHH
  HHHHH               HHHHH  
  HHHHH               HHHHH  
  HHHHH               HHHHH  
  HHHHH               HHHHH  
  HHHHH               HHHHH  
  HHHHH               HHHHH  
  HHHHHHHHHHHHHHHHHHHHHHHHH  
  HHHHHHHHHHHHHHHHHHHHHHHHH  
  HHHHHHHHHHHHHHHHHHHHHHHHH  
  HHHHH               HHHHH  
  HHHHH               HHHHH  
  HHHHH               HHHHH  
  HHHHH               HHHHH  
  HHHHH               HHHHH  
  HHHHH               HHHHH  
                    HHHHHHHHH
                     HHHHHHH 
                      HHHHH  
                       HHH   
                        H    


[None, None, None, None, None]

#### Text wrap

In [2]:
import textwrap

def wrap(string, max_width):
    # returns the string in sections with given width
    return textwrap.fill(string, max_width)
    
if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)

jajajaja
3
jaj
aja
ja


#### Designer door mat

In [18]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
N, M = map(int,input().split()) # hight, width
rep = '.|.'

# the first half of the doormat
for i in range(int((N-1)/2)):
    print(((2*i+1)*rep).center(M, '-'))

# print the welcome
print('WELCOME'.center(M,'-'))

# print second half of the doormat
for i in range(int((N-1)/2)-1,-1,-1):
    print(((2*i+1)*rep).center(M, '-'))

5 21
---------.|.---------
------.|..|..|.------
-------WELCOME-------
------.|..|..|.------
---------.|.---------


#### string formatting

In [19]:
def print_formatted(number):
    
    # for outline
    d = len(bin(number)[2:])
    
    # loop over the given number
    # the [2:] to retrieve correct number from given info
    for i in range(1, number+1):
        octal = oct(i)[2:]
        hexadec = hex(i)[2:].upper()
        binar = bin(i)[2:]
        # print the numbers
        # outline to the right
        print(str(i).rjust(d), octal.rjust(d),
              hexadec.rjust(d), binar.rjust(d))

if __name__ == '__main__':
    n = int(input())
    print_formatted(n)

11
   1    1    1    1
   2    2    2   10
   3    3    3   11
   4    4    4  100
   5    5    5  101
   6    6    6  110
   7    7    7  111
   8   10    8 1000
   9   11    9 1001
  10   12    A 1010
  11   13    B 1011


#### Alphabet rangoli

In [12]:
from string import ascii_lowercase as aph

def print_rangoli(size):
    # loop over twice the size to make the figure go back and forth
    for i in range(1,2*size):
        # make list with used letters
        letter = aph[abs(size-i):size]
        letter = letter[-1:0:-1] + letter
        # print the letters with '-'
        print('-'.join(letter).center(4*size-3,'-'))    
    
    
if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)

c
----c----
--c-b-c--
c-b-a-b-c
--c-b-c--
----c----


#### Capitalize!

In [14]:
#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):
    # make an empty list
    lst = []
    # split the name on the space
    name = s.split(" ")
    # loop over the name list and return with capital letter
    # add name to list
    for i in range(0, len(name)):
        lst.append(name[i].capitalize())
    
    return " ".join(lst) # make one name of the list
    
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()

KeyError: 'OUTPUT_PATH'

#### The minion game

In [17]:
def minion_game(string):
    stuartPoints =0
    kevinPoints =0
    vowls = ["A","E","I","O","U"]
    # loop over the letters in the string
    for i in range(len(string)):
        # if it is a vowel, the words following will start with vowel
        # kevin gets points
        if string[i] in vowls:
            kevinPoints += len(string)-i
        # else it starts with consonant, so stuart gets point
        else:
            stuartPoints += len(string)-i
    # if stuart has more points than Kevin, stuart wins
    if stuartPoints>kevinPoints:
        print("Stuart {}".format(stuartPoints))
    # equal is a draw
    elif(stuartPoints==kevinPoints):
        print("Draw")
    else:
        print("Kevin {}".format(kevinPoints))
    

if __name__ == '__main__':
    s = input()
    minion_game(s)

SEASICK
Draw


#### Merge the tools

In [18]:
# Used discussion to understand the aim of the exercise

def merge_the_tools(string, k):
    lngthStr = len(string)     # determine length of string
    ratio = lngthStr / k     # determine how many pieces are needed
    nr = k # initialize
    lst = [] # make empty list to store 
    # loop over the pieces of the string
    for i in range(0,lngthStr,k):
        # loop over the letters in the string
        for j in range(i,nr):
            # see if the specific letter is already a part of that string
            if string[j] not in lst:
                lst.append(string[j])
        print("".join(lst))
        # empty list again so it can be used for next iteration
        lst.clear()
        # add k to nr so it can be used for next iteration
        nr += k

if __name__ == '__main__':
    string, k = input(), int(input())
    merge_the_tools(string, k)

BABABDANR
4
BA
BDAN


IndexError: string index out of range

## Sets

#### Introduction to sets

In [22]:
def average(array):
    # determine the set
    setArr = set(array)
    # determine number of plants
    nr = len(setArr)
    # determine sum of array
    sumArr = sum(setArr)
    #return result
    return sumArr/nr
    
if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

2
2 2
2.0


#### No Idea!

In [8]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
def calculate_happy(arrayn, setA, setB):
    happyScore = 0 # initialize happyness score
    # loop over the elements in the array m
    for i in arrayn:
        if i in setA: # check if part of set A
            happyScore += 1
        if i in setB: # check if part of set B
            happyScore -= 1
    
    return happyScore

n1, m = map(int, input().split())
arrayn = list(map(int, input().split()))
setA = set(map(int, input().split()))
setB = set(map(int, input().split()))

# print the happy score
print(calculate_happy(arrayn, setA, setB))


3 2
1 5 3
3 1
5 7
1


#### Symmetric difference

In [23]:
def find_difference(listM, listN):
    # find the differences between the two sets
    diffN = listM.difference(listN) 
    diffM = listN.difference(listM)
    # make one set of them
    unionNM = diffN.union(diffM)
    
    # order them in correct order
    sortNM = sorted(unionNM)
    # print the elements
    for i in sortNM:
        print(i)
    

m = map(int, input().split()) # 4
listM = set(map(int, input().split())) #2 4 5 9
n = map(int, input().split()) # 4
listN = set(map(int, input().split())) # 2 4 11 12

find_difference(listM, listN)

4
2 4 5 9
4
2 4 11 12
5
9
11
12


#### Set .add()

In [25]:
n = int(input())
#make an empty set
countCountries = set()
for _ in range(n):
    countCountries.add(input())

# print the answer
print(len(countCountries))

KeyboardInterrupt: Interrupted by user

#### Set .discard(), .remove() & .pop

In [4]:
if __name__ == '__main__':
    n = int(input())
    setN = set(map(int, input().split()))
    N = int(input())
    
    # Loop over N to define the action
    for i in range(N):
        act = input().split()
        action = act[0]
        if action == 'pop':
            setN.pop()
        if action == 'remove':
            setN.remove(int(act[1]))
        if action == 'discard':
            setN.discard(int(act[1]))
        
    print(sum(setN))
    

3
1 2 3
2
pop
pop
3


#### Set .union() operator

In [6]:
def nrSubscription(setA, setB):
    # determine union of two sets
    setTot = setA.union(setB)
    # return the length of the set
    return len(setTot)

nrEnglish = int(input())
setEnglish = set(map(int, input().split()))
nrFrench = int(input())
setFrench = set(map(int, input().split()))

print(nrSubscription(setEnglish, setFrench))

4
1 2 3 4
4
1 2 3 6
5


#### set .intersection() operation

In [7]:
def nrSubscription(setA, setB):
    # determine intersection of two sets
    setTot = setA.intersection(setB)
    # return the length of the set
    return len(setTot)

nrEnglish = int(input())
setEnglish = set(map(int, input().split()))
nrFrench = int(input())
setFrench = set(map(int, input().split()))

print(nrSubscription(setEnglish, setFrench))

5
1 2 3 4 5
5
1 2 3 6 9
3


#### set .difference() operator

In [8]:
def nrSubscription(setA, setB):
    # determine difference of two sets
    setTot = setA.difference(setB)
    # return the length of the set
    return len(setTot)

nrEnglish = int(input())
setEnglish = set(map(int, input().split()))
nrFrench = int(input())
setFrench = set(map(int, input().split()))

print(nrSubscription(setEnglish, setFrench))

5
1 2 3 4 5
5
1 2 6 7 9
3


#### set .symmetric_difference operation

In [9]:
def nrSubscription(setA, setB):
    # determine symmetric difference of two sets
    setTot = setA.symmetric_difference(setB)
    # return the length of the set
    return len(setTot)

nrEnglish = int(input())
setEnglish = set(map(int, input().split()))
nrFrench = int(input())
setFrench = set(map(int, input().split()))

print(nrSubscription(setEnglish, setFrench))

5
1 2 3 4 5
5
1 2 6 7 9
6


#### Set mutations

In [11]:
nrSet = int(input())
setA = set(map(int,input().split()))
nrAction =int(input())

# loop over the number of the action
for _ in range(nrAction):
    # determine an action and a set
    action, t=input().split()
    setB = set(map(int,input().split()))
    if action =="update":
        setA.update(setB)
    elif action =="intersection_update":
        setA.intersection_update(setB)
    elif action =="difference_update":
        setA.difference_update(setB)
    elif action =="symmetric_difference_update":
        setA.symmetric_difference_update(setB)
# print the sum of the set after the actions
print(sum(setA))

16
 1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
intersection_update 10
 2 3 5 6 8 9 1 4 7 11
update 2
55 66
 symmetric_difference_update 5
 22 7 35 62 58
 difference_update 7
 11 22 35 55 58 62 66
38


#### The captain's room

In [13]:
# determine the captains room number
def captainsRoom(lst):
    # make a set of the list
    setRoom = set(lst)
    # loop over elements in set and remove from lst
    for i in setRoom:
        lst.remove(i)
    
    # return the difference between the lst and the set
    diffSet = setRoom.difference(set(lst))
    
    for i in diffSet:
        return i  


k = int(input()) 
lstRoom = list(map(int, input().split())) 

print(captainsRoom(lstRoom))

SyntaxError: invalid syntax (<ipython-input-13-bec07d874d61>, line 12)

#### Check subset

In [ ]:
n=int(input())
# loop over the cases
for x in range(n):
    # determine the sets
    nrA = int(input())
    setA = set(map(int,input().split()))
    nrB = int(input())
    setB = set(map(int,input().split()))
    
    # check if a is subset of b
    print(setA.issubset(setB))
    


#### Check strict superset

In [14]:
setA = set(map(int, input().split()))
n = int(input())

# loop over the sets
for i in range(n):
    # determine new set
    setB = set(map(int, input().split()))
    if not setA.issuperset(setB):
        print('False')
        break
    # check if last one is superset
    if (i == (n-1)) and (setA.issuperset(setB)):
        print('True')
    

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2
n 2 i 0
1 2 3 4 5
n 2 i 1
100 11 12
False


## Collections

#### Collections.counter()

In [22]:
nrShoes = int(input())
lstShoes = list(map(int, input().split()))
nrCust = int(input())

#initialize earned money
money = 0
# loop over the customers
for i in range(nrCust):
    # determine size and money
    size, costs = input().split()
    size = int(size)
    costs = int(costs)
    if (size in lstShoes):
        money += costs # add money
        lstShoes.remove(size) # remove size from list

print(money)
        

10
2 3 4 5 6 8 7 6 5 18
6
6 55
6 45
6 55
4 40
18 60
10 50
200


#### DefaultDict tutorial

In [23]:
from collections import defaultdict

sizeA, sizeB = map(int,input().split())

d = defaultdict(list)
# loop over A and make a list
for i in range(sizeA):
    d[input()].append(i+1)

# loop over size b
for i in range(sizeB):
    letterB = input()
    # check if the letter is in d
    if len(d[letterB])>0:
        print(*d[letterB])
    else:
        print(-1)
 

5 2
a
a
b
a
b
a
[1, 2, 4]
b
[3, 5]


#### Collections.namedtuple()

In [24]:
n = int(input())
string = input().split()
index = string.index("MARKS")

# initialize
total=0

# loop over the students
for i in range(n):
    grades = input().split()
    total += int(grades[index])

# print average
print(total/n)

5


KeyboardInterrupt: Interrupted by user

#### collections.OrderedDict()

In [35]:
from collections import OrderedDict

# make empty dictionary
orderedDict = {}

nrProducts = int(input())

# loop over the number of products
for _ in range(nrProducts):

    lst = input().split()
    price = int(lst[-1])

    name = ' '.join(map(str, lst[:-1]))
    
    # check if the name is already is in dictionary
    # in that case add price
    # otherwise make new key
    if name in orderedDict:
        orderedDict[name] += price
    else:
        orderedDict[name] = price

# print the products
for key, price in orderedDict.items():
    print (key, price)


3
ban 2
ban 3
jan 1
ban 5
jan 1


#### Word order

In [37]:
from collections import OrderedDict

nrWords = int(input())
dictionary = OrderedDict()

# loop over the number of words
for i in range(nrWords):
    # receive a word
    word = input()
    # see if word is in dictionary
    if word in dictionary:
        dictionary[word] = int(dictionary.get(word)) + 1
    else:
        dictionary[word] = 1
    
# print nr of words
print(len(dictionary))
# print the count
print(' '.join([str(dictionary.get(i)) for i in dictionary]))

4
bcdef
abcdefg
bcde
bcdef
3


TypeError: sequence item 0: expected str instance, tuple found

#### Collections.deque()

In [ ]:
from collections import deque

d = deque()
nrActions = int(input())

for i in range(nrActions):
    action = input().split()    
    if action[0] =='append':
        d.append(int(action[1]))    
    elif action[0] == 'appendleft':
        d.appendleft(int(action[1]))
    elif action[0] == 'pop':
        d.pop()
    elif action[0] == 'popleft':
        d.popleft()

# print the d
for element in d:
    print(element, end=' ')
    

#### Company logo

In [11]:
from itertools import groupby


import math
import os
import random
import re
import sys

def countLetters(string):
    
    # make a dictionary
    dictionary = {}
    
    for letter in string:
        # check if letter is in dictionary
        if letter in dictionary:
            dictionary[letter] = int(dictionary.get(letter)) + 1
        else:
            dictionary[letter] = 1
    
    
    #make a list of the dictionary
    lst = list(dictionary.keys())
    # sort the list on most appearing letter
    lst.sort()
    lst.sort(reverse=True, key=lambda k: dictionary[k])

    # print the count for the first three
    for element in lst[:3]:
        print(element, dictionary[element])
    


if __name__ == '__main__':
    s = input()
    countLetters(s)




qwertyuiopasdfghjklzxcvbnm
a 1
b 1
c 1


#### Piling up

In [ ]:
import math
def pileBlocks(blocks):
    # initialize the bottom
    bottom = math.inf
    # loop until there are no blocks left
    while blocks:
        # if the left block is bigger than the right block
        # and is smaller than the bottom, it can be stacked
        if blocks[0] >= blocks[-1] and blocks[0] <= bottom:
            bottom = blocks[0]
            # delete this block from the list
            del blocks[0]
            continue
        # if right block is bigger than left block
        # and smaller than the bottom, it can be stacked
        if blocks[-1] >= blocks[0] and blocks[-1] <= bottom:
            bottom = blocks[-1]
            del blocks[-1]
            continue
        # if not print false
        return print('No')
    # if print true
    return print('Yes')

if __name__ == '__main__':
    T = int(input())
    for _ in range(T):
        n = int(input())
        blocks = list(map(int, input().split()))
        pileBlocks(blocks)

## Date and time

#### Calendar module

In [15]:
import calendar

def findDay(day, month, year):
    # find nr weekday
    weekdayNr = calendar.weekday(year, month, day)
    # convert it to a string and return    
    return calendar.day_name[weekdayNr]

month, day, year = map(int,input().split())
# print in upper case
print(findDay(day, month, year).upper())


08 05 2015
WEDNESDAY


#### Time Delta

In [ ]:
from datetime import datetime

def time_delta(time1, time2):
    # used format
    time = "%a %d %b %Y %H:%M:%S %z"
    t1 = datetime.strptime(time1, time)
    t2 = datetime.strptime(time2, time)
    
    # return absolute value
    return str(abs(int((t1 - t2).total_seconds())))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        t1 = input()

        t2 = input()

        delta = time_delta(t1, t2)

        fptr.write(delta + '\n')

    fptr.close()


#### Exceptions

In [16]:
# loop over the test cases
for i in range(int(input())):
    try:
        # give a and b
        a,b = map(int,input().split())
        print(a//b)
    # give the corresponding error
    except Exception as e:
        print("Error Code:",e)

3
2 0
Error Code: integer division or modulo by zero
2 1
2
0 2
0


## Built-ins

#### Zipped!

In [17]:
student, subject = map(int,input().split())
grades = []
for _ in range(int(subject)):
    scores = list(map(float, input().split()))
    grades.append(scores)

for i in zip(grades):
    print(sum(i)/subjects)

KeyboardInterrupt: Interrupted by user

#### Athlete sort

In [22]:
import math
import os
import random
import re
import sys
import numpy as np

if __name__ == '__main__':
    nm = input().split()

    n = int(nm[0])
    m = int(nm[1])
    arr = []
    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    k = int(input())
    
    # sort the array
    dataArr =sorted(arr, key=lambda x: x[k])
    
    # print the list correctly
    for i in range(len(dataArr)):
        print(*dataArr[i])


3 2
1 2 3
3 2 1
4 4 4
1
1 2 3
3 2 1
4 4 4


#### ginortS

In [36]:
def sortWord (string):
    # make empty lists for four cases
    upperCase = []
    lowerCase = []
    evenNumber = []
    oddNumber = []
    
    # loop over symbols in string and add them to correct list
    # This will separate the four categories
    for i in range(len(string)):
        if string[i].isupper():
            upperCase.append(string[i])
        elif string[i].islower():
            lowerCase.append(string[i])
        elif int(string[i])% 2 == 0:
            evenNumber.append(string[i])
        else:
            oddNumber.append(string[i])
    
    # sort the four lists 
    upperCaseSort = sorted(upperCase)
    lowerCaseSort = sorted(lowerCase)
    evenNumberSort = sorted(evenNumber)
    oddNumberSort = sorted(oddNumber)
    
    # combine the lists
    combinedList = ''.join(lowerCaseSort)+''.join(upperCaseSort)+''.join(oddNumberSort)+''.join(evenNumberSort)
    
    # return the combined lists
    return combinedList



word = input()
print(sortWord(word))

aaaFWFqw112432
aaaqwFFW113242


## Python Functionals (map and lambda functions)

In [39]:
cube = lambda x: x**3 # complete the lambda function 

def fibonacci(n):
    
    # make empty list to store fibonacci numbers
    lstFib = []
    
    # loop over n
    for i in range(n):
        # return a list of fibonacci numbers
        # Check if n is 0
        # then it will return 0
        if i == 0:
            lstFib.append(0)
 
        # Check if n is 1,2
        elif i == 1 or i == 2:
            lstFib.append(1)
 
        else:
            lstFib.append(lstFib[i-1] + lstFib[i-2]) 
    
    return lstFib
 

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

7
[0, 1, 1, 8, 27, 125, 512]


## Regex and Parsing challenges

#### Detect floating point number

In [44]:
import re

def detectFloatPointNr(nrStrings):
    
    # loop over symbols in string
    for i in range(n):
        # make a new nr
        inputNr = input()
        # check if one of the conditions from exercise is met
        if re.match('^[+-]{0,1}[\d]{0,}\.\d+$', inputNr):
            print(True)
        else:
            print(False)
        

n = int(input())

detectFloatPointNr(4)

4
3.0
True
wao[quf
False
2.2
True
2.
False


#### Re.split()

In [ ]:
regex_pattern = r"[,.]"	# Do not delete 'r'.

import re
print("\n".join(re.split(regex_pattern, input())))

#### Group(), Groups() & Groupdict()

In [51]:
def findRepeat(string): 
    # make an empty set to store characters
    charSet = set()
    # loop over elements in string
    for element in string: 
        # if element is in the set, it is repeated and can be returned
        if element in charSet: 
            return element
        # else it should be checked if the element is alphanumeric 
        # and can be added to the set.
        elif element.isalnum(): 
            charSet.add(element)

    return -1

n = input()
print(findRepeat(n)) 

__init__
i


#### Re.findall() & Re.finditer()

In [55]:
# used the discussion section of hackerrank

import re

def findVowelsinConsonants(string):
    # define the repetition strings
    pattern = re.compile(r"(?<![AEIOU])([AEIOU]{2,})(?![AEIOU]).", re.I)
    # save the vowels from the pattern
    vowels = pattern.findall(string)
    if vowels:
        # print the vowels, seperated on each line
        print(*vowels, sep='\n')
    else:
        print(-1)
    
    


n = input()
findVowelsinConsonants(n)

qeeroijgo
ee
oi


#### Re.start() & Re.end()

In [64]:
# used the discussion section of hackerrank

import re

def partofString(string, partString):
    # see if substring is part of the string
    if re.search(r"" + partString + "", string):
        # find the start and end parts
        for string in re.finditer(r"(?=("+ partString +"))", string):
            print("(",string.start(1),", ",string.end(1)-1,")", sep='')
        
    # if it is not part of string
    else:
        print("(-1, -1)")
        

string = input()
partString = input()

partofString(string, partString)

aaabaa
aa
(0, 1)
(1, 2)
(4, 5)


#### Regex Substitution

In [ ]:
import re



def Replacement(check):
    string = str(check.group(0))
    if string == "||":
        return "or"
    elif string == "&&":
        return "and"

    
number = int(input())

# loop over the number
for i in range(number):
    # define the input
    string = input()
    # define tha pattern
    symbols = "(?<=[ ])[|]{2}(?=[ ])|(?<=[ ])[&]{2}(?=[ ])"
    # print the text
    print(re.sub(symbols, Replacement, string))

#### Validating Roman Numerals

In [65]:
def checkIfRoman(string):
    #possible roman letters
    RomanLetters = ["M", "D", "C", "L", "X", "V", "I", "(", ")"]
    #initialize boolean
    Roman = True
    # loop over the letters
    for letters in string:
        # change boolean if not roman letter
        if letters not in RomanLetters:
            Roman = False
            break
    return Roman

text = input()
print(checkIfRoman(text))

LL
True


#### Validating phone numbers

In [79]:
def validPhoneNr(nr):
    #loop over nr for different phone numbers
    for i in range(nr):
        string = input()
        # initialize boolean
        valid = False
        # check length of string and first symbol and only numbers
        if (string.isdecimal()) and (len(string) == 10) and (int(string[0]) == 7 or int(string[0]) == 8 or int(string[0]) == 9):
            valid = True
        # print yes or no
        if valid:
            print('YES')
        else:
            print('NO')

n = int(input())
PhoneNr = validPhoneNr(n)



2
987654321
NO
9087654321
YES


#### Validating and Parsing Email Addresses

In [ ]:
import re

# symbols and pattern used
symbols = re.compile(r"<[a-z][a-zA-Z0-9\-\.\_]+\@[a-zA-Z]+\.[a-zA-Z]{1,3}>")


for i in range(int(input())):
    mail = input().split()
    # check if pattern matches email
    patternTrue = symbols.search(mail[1])
    if patternTrue:
        print(mail[0], patternTrue.string)

#### Hex Color Code

In [ ]:
import re

# symbols
symbols = re.compile(r"[\s:](#[0-9A-Fa-f]{3,6})")
n = int(input())

# loop over the input range
for i in range(n):
    string = input()
    colors = symbols.findall(string)
    for i in colors:
        print(i)

#### HTML Parser - Part 1

In [ ]:
from html.parser import HTMLParser

# code is based on the notes of the exercise
class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print ('Start :', tag)
        for i in attrs:
            print(f"-> {i[0]} > {i[1]}")
    def handle_endtag(self, tag):
        print ('End   :', tag)
    def handle_startendtag(self, tag, attrs):
        print ('Empty :',tag)
        for i in attrs:
            print(f"-> {i[0]} > {i[1]}")

            
Nlines = int(input())    
parser = MyHTMLParser();

# print the lines and apply the MyHTMLParser
for i in range(Nlines):
    parser.feed(input())

#### HTML Parser - Part 2

In [ ]:
rom html.parser import HTMLParser
import re

class MyHTMLParser(HTMLParser):
    def handle_comment(self,data):
        # check for comments multi line
        if re.search(r"\n",data):
            print(">>> Multi-line Comment")
            print(data.rstrip())
        # otherwise the comment is single line
        else:
            print(">>> Single-line Comment")
            print(data.rstrip())
    
    # if the data is not '\n'
    def handle_data(self,data):
        if data != '\n':
            print(">>> Data")
            print(re.sub('\n','',data))

html = ""       
for i in range(int(input())):
    html += input().rstrip()
    html += '\n'
    
parser = MyHTMLParser()
parser.feed(html)
parser.close()

#### Detect HTML Tags, Attributes and Attribute Values

In [ ]:
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_starttag(self,label,attrs):
        print(label)
        for element in attrs:
            print('->',element[0],'>',element[1])
   
 
parser = MyHTMLParser()
for _ in range(int(input())):
    parser.feed(input())

#### Validating UID

In [ ]:
import re 
   
def validString(nr):
    # loop over the numbers and make a string
    for i in range(nr):
        string = input()
        # check if conditions are met
        if (len(string) == 10 and len(set(re.findall("\w",string))) == 10 
                and re.search("[^\w]", string) is None and len(re.findall("\d", string)) >= 3 and
                len(re.findall("[A-Z]",string)) >= 2):
            print('Valid')
        else:
            print("Invalid")
    
    

nr = int(input())
validString(nr)


#### Validating Credit Card Numbers

In [151]:
def validateCreditcard(nr):
    # loop over the number and make strings
    for i in range(nr):
        stringCC = input()
        #remove hyphen if in string
        #initialize x
        x = 0
        n = 4
        for i in stringCC:
            if x % n == 0 and i == '-' and not stringCC[x+1] == '-':
                lst = list(stringCC)
                lst[x] = ''
                stringCC = ''.join(lst)
                x -= 1
            x += 1
        
        # check if conditions are met
        if (stringCC[0] in '456' and len(stringCC) == 16
                and stringCC.isdecimal() and not any([str(i*1111) in stringCC for i in range(10)])):
            print('Valid')
        else:
            print('Invalid')
            

nr = int(input())
validateCreditcard(nr)

1
5123-4567-8912-3456
5123456789123456
Valid


#### Validating Postal Codes

In [ ]:
regex_integer_in_range = r"^[1-9]\d{5}$"	# Do not delete 'r'.
regex_alternating_repetitive_digit_pair = r"(?=(\d).\1)"	# Do not delete 'r'.


import re
P = input()

print (bool(re.match(regex_integer_in_range, P)) 
and len(re.findall(regex_alternating_repetitive_digit_pair, P)) < 2)

#### Matrix Script

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys


def findStringInMatrix(matrix):
    # make a list of the matrix
    lstMatrix = list(zip(*matrix))
    # Start an empty string
    string = ""
    # loop over the list
    for i in range(len(lstMatrix)):
        # add to the string
        string += "".join(lstMatrix[i])
    # make the pattern
    symbols = re.compile(r"(?<=\w)[!@#$%& ]{1,}(?=\s*\w)")
    # adjust string based on the pattern
    finalString = re.sub(symbols," ",string)
    return finalString
    


first_multiple_input = input().rstrip().split()

n = int(first_multiple_input[0])

m = int(first_multiple_input[1])

matrix = []

for _ in range(n):
    matrix_item = input()
    matrix.append(matrix_item)


print(findStringInMatrix(matrix))

## XML 
#### (used the discussion page for XML)

#### XML1 - Find the score

In [81]:
import sys
import xml.etree.ElementTree as etree

def get_attr_number(node):
    value = len(node.attrib) + sum([get_attr_number(i) for i in node])
    return value

if __name__ == '__main__':
    sys.stdin.readline()
    xml = sys.stdin.read()
    tree = etree.ElementTree(etree.fromstring(xml))
    root = tree.getroot()
    print(get_attr_number(root))

ParseError: no element found: line 1, column 0 (<string>)

#### XML2 - Find the maximum depth

In [ ]:
import xml.etree.ElementTree as etree

maxdepth = 0

def depth(elem, level):
    # initialize the maxdepth
    global maxdepth
    # check the level. if it is same, add one to maxdpth
    if (level == maxdepth):
        maxdepth += 1
    
    #loop over the elements to add to level if needed
    for i in elem:
        depth(i, level + 1)
    return level

if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)

## Closures and decorations

#### Standardize Mobile Number Using Decorators

In [ ]:
def wrapper(f):
    def fun(l):
        # make an empty list
        lst = []
        # make sure that phone numbers are correct layout
        for element in l:
            lst.append('+91 '+element[-10:-5]+' '+ element[-5:])
        # return the list so it can be sorted    
        return f(lst)
    return fun

@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

if __name__ == '__main__':
    l = [input() for _ in range(int(input()))]
    sort_phone(l) 




#### Decorators 2 - Name Directory

In [ ]:
import operator

def person_lister(f):
    def inner(people):
        # sort the people
        people.sort(key=lambda i: int(i[2]))
        return [f(x) for x in people]
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

## Numpy

#### Arrays

In [88]:
import numpy as np

def arrays(arr):
    # make the numpy array
    nparray =  np.array(arr,float)
    # return the reverse
    return np.flip(nparray)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


#### Shape and reshape

In [94]:

def shapeArray(string):
    nparray = numpy.fromstring(string, int, sep=' ')
    shapedArray = numpy.reshape(nparray,(3,3))
    return shapedArray

n = input()
print(shapeArray(n))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Transpose and flatten

In [123]:
def transAndFlat(rows, cols):
    # make an empty array
    arrayTF = np.zeros([rows, cols])
    for i in range(rows):
        # add the rows to np
        arrayTF[i] = np.fromstring(input(), int, sep=' ')
    
    # print the transpose
    print(arrayTF.T.astype(int))
    #print the flatten
    print(arrayTF.flatten().astype(int))
        

N, M = map(int, input().split())

transAndFlat(N, M)

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


#### Concatenate

In [131]:
def concatenate(row1, row2, col):
    
    # make two empty lists
    arrN = []
    arrM = []
    
   # make array N
    for _ in range(row1):
        arrN.append(np.array(list(map(int, input().split()))))
        
    #make array M
    for _ in range(row2):
        arrM.append(np.array(list(map(int, input().split()))))
    
    # concatenate
    combined = np.concatenate((arrN, arrM), axis=0)
    
    return combined

N, M, P = map(int, input().split())
print(concatenate(N, M, P))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


#### Zeros and ones

In [133]:
# 3 3 3
def zeros_ones(row, col, rep):
    # make zeros array
    zeros0 = numpy.zeros((row, col), dtype = numpy.int)
    # make ones array
    ones1 = numpy.ones((row, col), dtype = numpy.int)
    
    # make first iteration
    if rep >= 2:
        zeros = np.concatenate((zeros0, zeros0), axis=0)
        ones = np.concatenate((ones1, ones1), axis = 0)
    
    # concatenate everything
    for i in range(rep-1):
        zeros = np.concatenate((zeros, zeros0), axis=0)
    
    # concatenate everything
    for i in range(rep-1):
        ones = np.concatenate((ones, ones1), axis=0)
        
    return np.concatenate((zeros, ones), axis=0)
    
        
row, col, repeat = map(int, input().split())
print(zeros_ones(row, col, repeat))

3 3 3
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


#### Eye and identity

In [ ]:
row, col = map(int, input().split())
np.set_printoptions(legacy = '1.13')
print(np.eye(row, col, k = 0))

#### Array mathematics

In [134]:
N, M = np.array(input().split(), int)
a = np.array([input().split() for i in range(N)], int)
b = np.array([input().split() for i in range(N)], int)

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.floor_divide(a, b))
print(np.mod(a, b))
print(np.power(a, b))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


#### Floor, Ceil and Rint

In [135]:
np.set_printoptions(legacy='1.13')
array = np.array(input().split(), float)

print(np.floor(array))
print(np.ceil(array))
print(np.rint(array))

1 2 3 4 5 
[ 1.  2.  3.  4.  5.]
[ 1.  2.  3.  4.  5.]
[ 1.  2.  3.  4.  5.]


#### Sum and Prod

In [ ]:
n, m = map(int, input().split())

array = np.array([list(map(int, input().split())) for _ in range(n)])

sumarray = np.sum(array, axis=0)
print(np.prod(sumarray))

#### Min and Max

In [137]:
n, m = map(int, input().split())
array = np.array([list(map(int, input().split())) for _ in range(n)])
minarray = np.min(array, axis=1)
print(np.max(minarray))

2 2
1 2
3 4
3


#### Mean, Var, and Std

In [143]:
n, m = map(int,input().split())

array = np.array([list(map(int,input().split())) for _ in range(n)])

print(np.mean(array,1))
print(np.var(array,0))
print(round(np.std(array),11))



1 2
2 
[ 2.]
[ 0.]
0


#### Dot and cross

In [ ]:
n = int(input())
arrayA = np.array([list(map(int, input().split())) for _ in range (n)])
arrayB = np.array([list(map(int, input().split())) for _ in range (n)])
print(np.dot(arrayA,arrayB))

#### Inner and outer

In [ ]:
arrayA = np.array(list(map(int, input().split())))
arrayB = np.array(list(map(int, input().split())))
print(np.inner(arrayA,arrayB))
print(np.outer(arrayA,arrayB))

#### Polynomials

In [ ]:
P = list(map(float, input().split()))
x = int(input())

print(np.polyval(P, x))

#### Linear algebra

In [ ]:
N = int(input())
array = [list(map(float, input().split())) for _ in range(N)]
print(round(np.linalg.det(array),2))